is_debug: true

minio:
  endpoint: 127.0.0.1:9000
  use_ssl: false
  bucket: notes-files
rabbitmq:
  enabled: false
  url: amqp://guest:guest@localhost:5672/
  exchange: notes.events

listen:
  type: port
  bind_ip: 127.0.0.1
  port: "8085"

upload:
  max_file_size_mb: 32
