---

is_debag: true
jwt:
  secret: $3cr3t
listen:
  type: port
  bind_ip: localhost
  port: 8080
category_service:
  url: http://localhost:8081/api
note_service:
  url: http://localhost:8082/api
file_service:
  url: http://localhost:8085/api
user_service:
  url: http://localhost:8083/api
