### health
GET http://localhost:8083/health

### create user
POST http://localhost:8083/api/users
Content-Type: application/json

{
  "username": "me",
  "email": "me@example.com",
  "password": "pass"
}

### get user
GET http://localhost:8083/api/users/{{user_uuid}}

### auth user
POST http://localhost:8083/api/users/authenticate
Content-Type: application/json

{
  "username": "me",
  "password": "pass"
}
