is_debug: true
postgres:
  host: localhost
  port: 5433
  username: notes_user
  password: notes_password
  database: users_system
  ssl_mode: disable
listen:
  type: port
  bind_ip: localhost
  port: 8083
