debug: true
log_level: DEBUG
logger_name: category_service
app_host: 0.0.0.0
app_port: 8081
app_title: Category Service
api_prefix: /api
cors_allowed_origins:
  - http://localhost:3000
  - http://localhost:5173
neo4j_scheme: bolt
neo4j_hostname: localhost
neo4j_port: 7687
neo4j_login: neo4j
neo4j_password: testtest
neo4j_database: neo4j
rabbitmq_enabled: false
rabbitmq_url: amqp://guest:guest@localhost:5672/
rabbitmq_exchange: notes.events
rabbitmq_note_updated_queue: category.note-updated
rabbitmq_note_updated_routing_key: note.updated
