services:
  neo4j:
    image: neo4j:2026.02.2
    container_name: ns-cs-neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./export/neo4j/data:/data
      - ./export/neo4j/conf:/conf
      - ./export/neo4j/logs:/logs
      - ./export/neo4j/import:/import
      - ./export/neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/testtest
      NEO4J_PLUGINS: '["apoc"]'
